# Defines the start of the services (containers) that make up your app
services:

  # This is the name of your first service (your FastAPI backend)
  server:
    # Tells Docker how to build the image for this container
    build:
      # The folder Docker should look in for the Dockerfile and code
      context: ./backend  
    # This pulls variables from your root .env and injects them into the container
    env_file:
      - ./.env
    # Maps ports: "Host Port (Your Laptop) : Container Port (The App)"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src # Use this instead if your Dockerfile says WORKDIR /src
    # Sets environment variables inside the container
    environment:
      # Injects the DATABASE_URL from your .env file into the container
      - DATABASE_URL=${DATABASE_URL}
    # This overrides the Dockerfile CMD specifically for your local machine
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # Sets the startup order
    depends_on:
      # Tells the server to wait for the 'db' service
      db:
        # Specifically wait until the 'db' passes its healthcheck (below)
        condition: service_healthy

  # This is the name of your second service (the database)
  db:
    # The pre-built image to download from Docker Hub
    image: postgres:16-alpine
    
    # If the DB crashes or the computer restarts, start this container again
    restart: always
    
    # Configuration variables required by the official Postgres image
    environment:
      # Sets the superuser name using your .env variable
      - POSTGRES_USER=${POSTGRES_USER}
      # Sets the superuser password using your .env variable
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Sets the default database name to create on startup
      - POSTGRES_DB=${POSTGRES_DB}
    
    # Allows you to connect to the DB from your laptop (DBeaver, etc.)
    ports:
      - "5432:5432"
    
    # Persistent storage
    volumes:
      # "Volume Name : Path inside the container where Postgres stores data"
      - db-data:/var/lib/postgresql/data
    
    # A script that runs inside the container to check if it's actually "ready"
    healthcheck:
      # The command to run (-U is user, -d is database)
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      # How long to wait between checks
      interval: 5s
      # How long to wait for a single check to respond before failing
      timeout: 5s
      # How many times to fail before marking the container as "unhealthy"
      retries: 5

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/src       
      - /src/node_modules      
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - server
# Defines named volumes that are shared across the whole project
volumes:
  # This matches the name used in the 'db' service above
  db-data:
