"""cart

Revision ID: 632f399ca764
Revises: c97ec5ae463e
Create Date: 2026-02-11 16:12:49.061558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '632f399ca764'
down_revision: Union[str, Sequence[str], None] = 'c97ec5ae463e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Cart', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    op.drop_column('Cart', 'user_id')
    # ### end Alembic commands ###
