"""added checkout details to order

Revision ID: 94abc8d17c36
Revises: f9b2398b0134
Create Date: 2026-03-14 02:07:53.560339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94abc8d17c36'
down_revision: Union[str, Sequence[str], None] = 'f9b2398b0134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Order', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('Order', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('Order', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'address')
    op.drop_column('Order', 'latitude')
    op.drop_column('Order', 'longitude')
    op.drop_column('Order', 'phone_number')
    # ### end Alembic commands ###
