"""cartitems naming fix

Revision ID: 9e65cc5ab87f
Revises: 632f399ca764
Create Date: 2026-02-13 16:08:00.846417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e65cc5ab87f'
down_revision: Union[str, Sequence[str], None] = '632f399ca764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CartItems_id'), table_name='CartItems')
    op.drop_table('CartItems')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CartItems',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.id'], name=op.f('CartItems_cart_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], name=op.f('CartItems_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'cart_id', 'product_id', name=op.f('CartItems_pkey'))
    )
    op.create_index(op.f('ix_CartItems_id'), 'CartItems', ['id'], unique=False)
    # ### end Alembic commands ###
