"""removed composite primarykeys and changed order/oderitem

Revision ID: ef452930bb09
Revises: 9e65cc5ab87f
Create Date: 2026-02-16 12:28:01.478868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef452930bb09'
down_revision: Union[str, Sequence[str], None] = '9e65cc5ab87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('Order', sa.Column('total_price', sa.Integer(), nullable=False))
    op.add_column('Order', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'Order', 'User', ['user_id'], ['id'])
    op.add_column('OrderItem', sa.Column('order_id', sa.Uuid(), nullable=False))
    op.add_column('OrderItem', sa.Column('price_at_purchase', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('OrderItem_user_id_fkey'), 'OrderItem', type_='foreignkey')
    op.create_foreign_key(None, 'OrderItem', 'Order', ['order_id'], ['id'])
    op.drop_column('OrderItem', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderItem', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'OrderItem', type_='foreignkey')
    op.create_foreign_key(op.f('OrderItem_user_id_fkey'), 'OrderItem', 'User', ['user_id'], ['id'])
    op.drop_column('OrderItem', 'price_at_purchase')
    op.drop_column('OrderItem', 'order_id')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_column('Order', 'status')
    op.drop_column('Order', 'total_price')
    op.drop_column('Order', 'user_id')
    # ### end Alembic commands ###
